# permissions for end users to view controllers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - controllers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - controllers/status
  verbs:
  - get
